"""MySQL-DDL für die relationale Zieldatenhaltung von Mercator."""

MYSQL_SCHEMA_STATEMENTS: list[str] = [
    """
    CREATE TABLE IF NOT EXISTS companies (
        company_key VARCHAR(64) NOT NULL,
        company_cik VARCHAR(32) NULL UNIQUE,
        current_symbol VARCHAR(20) NULL,
        company_name VARCHAR(255) NULL,
        profile_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED',
        profile_reason VARCHAR(255) NULL,
        first_seen_at DATETIME NULL,
        last_seen_at DATETIME NULL,
        market_cap BIGINT NULL,
        price DECIMAL(18,4) NULL,
        currency VARCHAR(10) NULL,
        isin VARCHAR(32) NULL,
        cusip VARCHAR(32) NULL,
        exchange VARCHAR(64) NULL,
        exchange_full_name VARCHAR(128) NULL,
        exchange_name VARCHAR(128) NULL,
        industry VARCHAR(128) NULL,
        sector VARCHAR(128) NULL,
        sector_raw VARCHAR(128) NULL,
        sector_normalized VARCHAR(128) NULL,
        sector_source VARCHAR(64) NULL,
        sector_resolution_method VARCHAR(64) NULL,
        sector_resolution_status VARCHAR(32) NOT NULL DEFAULT 'UNRESOLVED',
        profile_enriched_at DATETIME NULL,
        profile_provider VARCHAR(64) NULL,
        country VARCHAR(64) NULL,
        website VARCHAR(255) NULL,
        description TEXT NULL,
        ceo VARCHAR(255) NULL,
        full_time_employees VARCHAR(32) NULL,
        ipo_date DATE NULL,
        balance_sheet_quality VARCHAR(32) NULL,
        sector_business_quality VARCHAR(32) NULL,
        is_etf BOOLEAN NULL,
        is_actively_trading BOOLEAN NULL,
        is_adr BOOLEAN NULL,
        is_fund BOOLEAN NULL,
        profile_updated_at DATETIME NULL,
        source_system VARCHAR(32) NOT NULL DEFAULT 'fmp',
        trade_republic_universe_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        trade_republic_match_method VARCHAR(32) NOT NULL DEFAULT 'NONE',
        trade_republic_match_confidence VARCHAR(16) NOT NULL DEFAULT 'LOW',
        trade_republic_source_refreshed_at DATETIME NULL,
        trade_republic_reference_isin VARCHAR(32) NULL,
        trade_republic_reference_name VARCHAR(255) NULL,
        sync_version BIGINT NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (company_key),
        UNIQUE KEY uq_companies_current_symbol (current_symbol),
        INDEX idx_companies_current_symbol (current_symbol),
        INDEX idx_companies_sector (sector),
        INDEX idx_companies_country (country),
        INDEX idx_companies_exchange (exchange)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS insider_trades (
        id BIGINT NOT NULL AUTO_INCREMENT,
        company_key VARCHAR(64) NOT NULL,
        symbol_at_trade VARCHAR(20) NULL,
        filing_date DATE NULL,
        transaction_date DATE NULL,
        reporting_cik VARCHAR(32) NULL,
        company_cik VARCHAR(32) NULL,
        reporting_name VARCHAR(255) NULL,
        type_of_owner VARCHAR(255) NULL,
        transaction_type VARCHAR(64) NULL,
        acquisition_or_disposition CHAR(1) NULL,
        direct_or_indirect CHAR(1) NULL,
        form_type VARCHAR(16) NULL,
        security_name VARCHAR(255) NULL,
        normalized_instrument_type VARCHAR(64) NULL,
        transaction_code_class VARCHAR(32) NULL,
        qty BIGINT NULL,
        price DECIMAL(18,4) NULL,
        trade_value_estimated DECIMAL(20,4) NULL,
        filing_age_days INT NULL,
        trade_value DECIMAL(20,4) NULL,
        company_name VARCHAR(255) NULL,
        market_cap BIGINT NULL,
        industry VARCHAR(128) NULL,
        cik VARCHAR(32) NULL,
        isin VARCHAR(32) NULL,
        cusip VARCHAR(32) NULL,
        relative_trade_value_market_cap DECIMAL(12,6) NULL,
        relative_trade_value_20d_volume DECIMAL(12,6) NULL,
        same_insider_cluster_flag BOOLEAN NOT NULL DEFAULT FALSE,
        multi_insider_same_symbol_cluster_count INT NOT NULL DEFAULT 1,
        exchange_variants_count INT NULL,
        primary_exchange VARCHAR(64) NULL,
        available_exchanges JSON NULL,
        has_us_primary_listing BOOLEAN NULL,
        has_eu_listing_variant BOOLEAN NULL,
        exchange_resolution_confidence VARCHAR(16) NULL,
        listing_quality_score DECIMAL(6,2) NULL,
        tradability_proxy_score DECIMAL(6,2) NULL,
        broker_match_precheck_score DECIMAL(6,2) NULL,
        core_insider_score DECIMAL(6,2) NULL,
        investability_score DECIMAL(6,2) NULL,
        execution_score DECIMAL(6,2) NULL,
        trade_republic_score DECIMAL(6,2) NULL,
        final_score DECIMAL(6,2) NULL,
        final_class CHAR(1) NULL,
        decision_status VARCHAR(32) NULL,
        earnings_distance_days INT NULL,
        avg_20d_volume DECIMAL(20,2) NULL,
        avg_20d_dollar_volume DECIMAL(20,2) NULL,
        sma_50 DECIMAL(18,4) NULL,
        sma_200 DECIMAL(18,4) NULL,
        momentum_3m DECIMAL(12,6) NULL,
        momentum_6m DECIMAL(12,6) NULL,
        technical_state VARCHAR(32) NULL,
        liquidity_state VARCHAR(32) NULL,
        risk_reward_state VARCHAR(32) NULL,
        tr_availability_state VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        tr_tradability_state VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        tr_match_confidence VARCHAR(16) NOT NULL DEFAULT 'LOW',
        manual_review BOOLEAN NOT NULL DEFAULT FALSE,
        validation_status VARCHAR(32) NOT NULL DEFAULT 'VALID',
        dashboard_valid BOOLEAN NOT NULL DEFAULT FALSE,
        gate_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
        gate_reason VARCHAR(255) NULL,
        score DECIMAL(6,2) NULL,
        score_class CHAR(1) NULL,
        profile_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED',
        profile_reason VARCHAR(255) NULL,
        trade_republic_universe_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        trade_republic_match_method VARCHAR(32) NOT NULL DEFAULT 'NONE',
        trade_republic_match_confidence VARCHAR(16) NOT NULL DEFAULT 'LOW',
        trade_republic_source_refreshed_at DATETIME NULL,
        trade_republic_reference_isin VARCHAR(32) NULL,
        trade_republic_reference_name VARCHAR(255) NULL,
        source_url VARCHAR(512) NULL,
        dedupe_key CHAR(64) NOT NULL,
        fetched_at DATETIME NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_insider_trades_dedupe_key (dedupe_key),
        INDEX idx_insider_trades_company_key (company_key),
        INDEX idx_insider_trades_symbol_at_trade (symbol_at_trade),
        INDEX idx_insider_trades_filing_date (filing_date),
        INDEX idx_insider_trades_transaction_date (transaction_date),
        INDEX idx_insider_trades_gate_status (gate_status),
        CONSTRAINT fk_insider_trades_company_key
            FOREIGN KEY (company_key) REFERENCES companies(company_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS company_trade_stats (
        company_key VARCHAR(64) NOT NULL,
        trade_count BIGINT NOT NULL DEFAULT 0,
        buy_count BIGINT NOT NULL DEFAULT 0,
        sell_count BIGINT NOT NULL DEFAULT 0,
        last_trade_date DATE NULL,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (company_key),
        CONSTRAINT fk_company_trade_stats_company_key
            FOREIGN KEY (company_key) REFERENCES companies(company_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS market_signal_cache (
        symbol VARCHAR(20) NOT NULL,
        lookback_from DATE NOT NULL,
        lookback_to DATE NOT NULL,
        avg_20d_volume DECIMAL(20,2) NULL,
        avg_20d_dollar_volume DECIMAL(20,2) NULL,
        sma_50 DECIMAL(18,4) NULL,
        sma_200 DECIMAL(18,4) NULL,
        momentum_3m DECIMAL(12,6) NULL,
        momentum_6m DECIMAL(12,6) NULL,
        technical_state VARCHAR(32) NOT NULL,
        liquidity_state VARCHAR(32) NOT NULL,
        source_refreshed_at DATETIME NOT NULL,
        raw_row_count INT NULL,
        cache_status VARCHAR(32) NOT NULL DEFAULT 'READY',
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (symbol),
        INDEX idx_market_signal_cache_refreshed_at (source_refreshed_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS app_data_state (
        state_key VARCHAR(64) NOT NULL,
        state_version BIGINT NOT NULL DEFAULT 1,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (state_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS trade_republic_universe_reference (
        isin VARCHAR(32) NOT NULL,
        symbol VARCHAR(32) NULL,
        instrument_name VARCHAR(255) NULL,
        country VARCHAR(64) NULL,
        asset_class VARCHAR(64) NULL,
        source_url VARCHAR(512) NOT NULL,
        source_last_refreshed_at DATETIME NOT NULL,
        source_hash CHAR(64) NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (isin),
        INDEX idx_tr_universe_symbol (symbol)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS trade_republic_universe_meta (
        source_url VARCHAR(512) NOT NULL,
        source_type VARCHAR(32) NULL,
        source_last_refreshed_at DATETIME NULL,
        source_hash CHAR(64) NULL,
        instrument_count INT NOT NULL DEFAULT 0,
        valid_rows INT NULL,
        invalid_rows INT NULL,
        last_import_status VARCHAR(32) NULL,
        last_error TEXT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (source_url)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS app_filter_settings (
        id BIGINT NOT NULL AUTO_INCREMENT,
        setting_scope VARCHAR(64) NOT NULL,
        setting_key VARCHAR(128) NOT NULL,
        setting_value_json JSON NOT NULL,
        source_system VARCHAR(32) NOT NULL DEFAULT 'app',
        sync_version BIGINT NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_app_filter_settings_scope_key (setting_scope, setting_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS app_runtime_preferences (
        id BIGINT NOT NULL AUTO_INCREMENT,
        preference_key VARCHAR(128) NOT NULL,
        preference_value_json JSON NOT NULL,
        source_system VARCHAR(32) NOT NULL DEFAULT 'app',
        sync_version BIGINT NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_app_runtime_preferences_key (preference_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS app_sync_state (
        state_key VARCHAR(64) NOT NULL,
        pending_uni_sync BOOLEAN NOT NULL DEFAULT FALSE,
        sync_in_progress BOOLEAN NOT NULL DEFAULT FALSE,
        last_start_mode VARCHAR(32) NULL,
        last_requested_target VARCHAR(16) NULL,
        last_active_target VARCHAR(16) NULL,
        last_sync_direction VARCHAR(32) NULL,
        last_sync_status VARCHAR(32) NULL,
        last_sync_error TEXT NULL,
        last_sync_started_at DATETIME NULL,
        last_sync_finished_at DATETIME NULL,
        last_successful_uni_sync_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (state_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS app_api_usage (
        day_key DATE NOT NULL,
        provider VARCHAR(32) NOT NULL,
        call_count INT NOT NULL DEFAULT 0,
        limit_count INT NOT NULL DEFAULT 250,
        last_request_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (day_key, provider)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS watchlist_items (
        id BIGINT NOT NULL AUTO_INCREMENT,
        symbol VARCHAR(20) NOT NULL,
        company_key VARCHAR(64) NULL,
        display_name VARCHAR(255) NULL,
        notes TEXT NULL,
        priority INT NOT NULL DEFAULT 0,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        resolution_status VARCHAR(32) NOT NULL DEFAULT 'UNRESOLVED',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_watchlist_items_symbol (symbol),
        INDEX idx_watchlist_items_company_key (company_key),
        INDEX idx_watchlist_items_active_priority (active, priority),
        CONSTRAINT fk_watchlist_items_company_key
            FOREIGN KEY (company_key) REFERENCES companies(company_key)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS stock_price_history (
        symbol VARCHAR(20) NOT NULL,
        price_date DATE NOT NULL,
        open_price DECIMAL(18,4) NULL,
        high_price DECIMAL(18,4) NULL,
        low_price DECIMAL(18,4) NULL,
        close_price DECIMAL(18,4) NULL,
        adjusted_close DECIMAL(18,4) NULL,
        volume BIGINT NULL,
        provider VARCHAR(32) NOT NULL,
        source_refreshed_at DATETIME NULL,
        quality_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (symbol, price_date, provider),
        UNIQUE KEY uq_stock_price_history_symbol_date_provider (symbol, price_date, provider),
        INDEX idx_stock_price_history_symbol_date (symbol, price_date),
        INDEX idx_stock_price_history_quality_status (quality_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS fundamental_metrics (
        id BIGINT NOT NULL AUTO_INCREMENT,
        symbol VARCHAR(20) NOT NULL,
        metric_name VARCHAR(128) NOT NULL,
        period_type VARCHAR(32) NOT NULL,
        period_end DATE NOT NULL,
        value DECIMAL(24,8) NULL,
        unit VARCHAR(32) NULL,
        provider VARCHAR(32) NOT NULL,
        source_refreshed_at DATETIME NULL,
        quality_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_fundamental_metrics_symbol_metric_period_provider (
            symbol, metric_name, period_type, period_end, provider
        ),
        INDEX idx_fundamental_metrics_symbol_period (symbol, period_end),
        INDEX idx_fundamental_metrics_quality_status (quality_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS technical_features (
        symbol VARCHAR(20) NOT NULL,
        feature_date DATE NOT NULL,
        momentum_1m DECIMAL(12,6) NULL,
        momentum_3m DECIMAL(12,6) NULL,
        momentum_6m DECIMAL(12,6) NULL,
        sma_20 DECIMAL(18,4) NULL,
        sma_50 DECIMAL(18,4) NULL,
        sma_200 DECIMAL(18,4) NULL,
        volatility_20d DECIMAL(12,6) NULL,
        max_drawdown_1y DECIMAL(12,6) NULL,
        volume_trend_20d DECIMAL(12,6) NULL,
        feature_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        unavailable_reason TEXT NULL,
        input_refreshed_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (symbol, feature_date),
        UNIQUE KEY uq_technical_features_symbol_date (symbol, feature_date),
        INDEX idx_technical_features_status (feature_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS fundamental_features (
        symbol VARCHAR(20) NOT NULL,
        feature_period DATE NOT NULL,
        revenue_growth DECIMAL(12,6) NULL,
        earnings_growth DECIMAL(12,6) NULL,
        gross_margin DECIMAL(12,6) NULL,
        operating_margin DECIMAL(12,6) NULL,
        net_margin DECIMAL(12,6) NULL,
        valuation_ratio DECIMAL(18,6) NULL,
        debt_to_equity DECIMAL(18,6) NULL,
        market_cap BIGINT NULL,
        feature_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
        unavailable_reason TEXT NULL,
        input_refreshed_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (symbol, feature_period),
        UNIQUE KEY uq_fundamental_features_symbol_period (symbol, feature_period),
        INDEX idx_fundamental_features_status (feature_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS model_runs (
        model_run_id VARCHAR(64) NOT NULL,
        model_name VARCHAR(128) NOT NULL,
        model_type VARCHAR(64) NOT NULL,
        model_version VARCHAR(64) NOT NULL,
        target_type VARCHAR(64) NOT NULL,
        horizon_days INT NOT NULL,
        training_started_at DATETIME NULL,
        training_completed_at DATETIME NULL,
        training_window_start DATE NULL,
        training_window_end DATE NULL,
        feature_set_version VARCHAR(64) NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
        quality_summary_json JSON NULL,
        error_message TEXT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (model_run_id),
        INDEX idx_model_runs_name_version (model_name, model_version),
        INDEX idx_model_runs_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS prediction_results (
        prediction_id BIGINT NOT NULL AUTO_INCREMENT,
        model_run_id VARCHAR(64) NOT NULL,
        symbol VARCHAR(20) NOT NULL,
        prediction_as_of DATE NOT NULL,
        horizon_days INT NOT NULL,
        target_type VARCHAR(64) NOT NULL,
        direction VARCHAR(32) NULL,
        return_class VARCHAR(32) NULL,
        expected_return DECIMAL(12,6) NULL,
        confidence DECIMAL(12,6) NULL,
        uncertainty DECIMAL(12,6) NULL,
        model_quality_score DECIMAL(12,6) NULL,
        input_refreshed_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (prediction_id),
        UNIQUE KEY uq_prediction_results_run_symbol_as_of (
            model_run_id, symbol, prediction_as_of, horizon_days, target_type
        ),
        INDEX idx_prediction_results_symbol_as_of (symbol, prediction_as_of),
        CONSTRAINT fk_prediction_results_model_run_id
            FOREIGN KEY (model_run_id) REFERENCES model_runs(model_run_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS backtest_results (
        backtest_id BIGINT NOT NULL AUTO_INCREMENT,
        model_run_id VARCHAR(64) NOT NULL,
        horizon_days INT NOT NULL,
        evaluation_start DATE NULL,
        evaluation_end DATE NULL,
        sample_size INT NULL,
        accuracy DECIMAL(12,6) NULL,
        precision_score DECIMAL(12,6) NULL,
        recall_score DECIMAL(12,6) NULL,
        mean_absolute_error DECIMAL(18,8) NULL,
        calibration_summary_json JSON NULL,
        caveats_text TEXT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (backtest_id),
        INDEX idx_backtest_results_model_run_id (model_run_id),
        CONSTRAINT fk_backtest_results_model_run_id
            FOREIGN KEY (model_run_id) REFERENCES model_runs(model_run_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS preference_scores (
        preference_score_id BIGINT NOT NULL AUTO_INCREMENT,
        symbol VARCHAR(20) NOT NULL,
        score_as_of DATE NOT NULL,
        preference_score DECIMAL(12,6) NULL,
        rank_position INT NULL,
        fundamental_component DECIMAL(12,6) NULL,
        technical_component DECIMAL(12,6) NULL,
        risk_component DECIMAL(12,6) NULL,
        prediction_component DECIMAL(12,6) NULL,
        confidence_component DECIMAL(12,6) NULL,
        confidence DECIMAL(12,6) NULL,
        uncertainty DECIMAL(12,6) NULL,
        explanation_positive TEXT NULL,
        explanation_negative TEXT NULL,
        data_quality_summary TEXT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (preference_score_id),
        UNIQUE KEY uq_preference_scores_symbol_as_of (symbol, score_as_of),
        INDEX idx_preference_scores_rank (score_as_of, rank_position)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS import_runs (
        import_run_id VARCHAR(64) NOT NULL,
        provider VARCHAR(32) NOT NULL,
        import_type VARCHAR(64) NOT NULL,
        started_at DATETIME NOT NULL,
        completed_at DATETIME NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
        symbols_requested INT NOT NULL DEFAULT 0,
        symbols_succeeded INT NOT NULL DEFAULT 0,
        symbols_failed INT NOT NULL DEFAULT 0,
        raw_responses_written INT NOT NULL DEFAULT 0,
        clean_records_written INT NOT NULL DEFAULT 0,
        error_message TEXT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (import_run_id),
        INDEX idx_import_runs_provider_type (provider, import_type),
        INDEX idx_import_runs_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    """
    CREATE TABLE IF NOT EXISTS data_quality_issues (
        issue_id BIGINT NOT NULL AUTO_INCREMENT,
        symbol VARCHAR(20) NOT NULL,
        data_category VARCHAR(64) NOT NULL,
        severity VARCHAR(32) NOT NULL,
        status VARCHAR(32) NOT NULL,
        message TEXT NOT NULL,
        detected_at DATETIME NOT NULL,
        source_refreshed_at DATETIME NULL,
        resolved_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (issue_id),
        INDEX idx_data_quality_issues_symbol_category (symbol, data_category),
        INDEX idx_data_quality_issues_status_severity (status, severity)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
]

# Offene Architekturpunkte sind zentral in ``docs/todos_offene_fragen.md`` dokumentiert.
