$lualatex = 'lualatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex = 'biber %O %B';
$pdf_mode = 4;
$max_repeat = 5;

add_cus_dep('glo', 'gls', 0, 'makeglossaries');
sub makeglossaries {
    my ($base_name, $path) = fileparse( $_[0] );
    my $return = system( "makeglossaries \"$base_name\"" );
    return $return;
}
