[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

